# circle ci config (github)
version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:22.04

    steps:
      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Installing BUILD-ESSENTIAL
          command: 'apt-get update && apt-get install -y build-essential'

      - run:
          name: Install kernel soruces
          command: 'apt-get update && apt-get install -y linux-headers-6.1.0-1010-oem'

      - run:
          name: Installing GIT
          environment:
            TZ: "America/Los_Angeles"
            DEBIAN_FRONTEND: "noninteractive"
          command: 'apt-get update && apt-get install -y git'

      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc-12'

      - checkout

## preparations
      - run:
          name: Preparations
          command: |
              mkdir -p /lib/modules/$(uname -r)
              cd /lib/modules/$(uname -r)
              ln -s /lib/modules/6.1.0-1010-oem/build build

## 00: basics
      - run: cd basics01__hello && make
      - run: cd basics02__hello && make
      - run: cd basics03__hello && make
      - run: cd basics04__hello_module_init_arguments && make
      - run: cd basics05__hello_module_init_arguments && make
      - run: cd basics06__hello_multiple_files && make
      - run: cd basics07__hello_chardev_driver && make
      - run: cd basics08__hello_procfs_read && make
      - run: cd basics09__hello_procfs_read_write && make
      - run: cd basics10__hello_procfs_fops && make
      - run: cd basics11__hello_procfs_seq_filesystem && make
      - run: cd basics12__hello-with-timing && KERNELDIR=/lib/modules/$(uname -r)/build ARCH=x86 CROSS_COMPILE=" " make
      - run: cd kbuild__symbol_export_to_another_module && make
      - run: cd gpio__raspi4_led && make
      - run: cd gpio__raspi4_interrupt && make
      - run: cd kthread && make
      - run: cd kthread__atomic_operation && make
      - run: cd kthread__mutex && make
      - run: cd kthread__spinlock && make
      - run: cd kthread__rwlock && make
      - run: cd kthread__rcu && make
      - run: cd kthread__completion && make
      - run: cd kthread__completion_dynamic && make
      - run: cd kthread__seqlock && make
      - run: cd sysfs && make
      - run: cd chardev__01_mknod && make
      - run: cd chardev__02_devicefile && make
      - run: cd chardev__03_devicefile_and_chardev && make
      - run: cd chardev__04_devicefile_implemented && make
      - run: cd chardev__ioctl01 && make
      - run: cd chardev__ioctl02_string_disabled && make
      - run: cd chardev__ioctl03_signal && make
      - run: cd chardev__wait_on_events && make
      - run: cd chardev__linkedlist && make
      - run: cd device__01_static_major_minor && make
      - run: cd device__02_dynamic_major_minor && make
      - run: cd interrupt && make
      - run: cd interrupt__workqueue01_kernel && make
      - run: cd interrupt__workqueue02_customized && make
      - run: cd interrupt__tasklet01 && make
      - run: cd interrupt__tasklet02__dynamic_alloc && make
      - run: cd timer && make
      - run: cd timer__hres_timer && make
      - run: cd usb__basic && make
      - run: cd usb__descriptors && make

