name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: tuning, disable initramfs update
        run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf

      - name: tuning, disable man-db update
        run: sudo rm -f /var/lib/man-db/auto-update

      - name: install build-essential
        run: |
          sudo apt-get update
          sudo apt-get install -y crossbuild-essential-arm64

      - name: install gcc/g++
        run: |
          sudo apt-get install -y gcc g++

      - name: install debhelper
        run: |
          sudo apt-get install -y debhelper

      - name: install DT compiler
        run: |
          sudo apt-get install -y device-tree-compiler

      - name: install libc6-dev
        run: |
          sudo apt-get install -y libc6-dev

      - name: install cunit
        run: |
          sudo apt-get install -y libcunit1-ncurses-dev

      - name: install clang
        run: |
          sudo apt-get install -y clang clang-tools clang-format

      - name: install cmake
        run: |
          sudo apt-get install -y cmake

      - name: rpi kernel sources
        run: |
          export LINUX_BRANCH="rpi-6.3.y"
          export KDEFCONFIG_NAME="bcm2711_defconfig"
          export KERNEL_URL="https://github.com/raspberrypi/linux"
          sudo chown $(whoami):$(whoami) -R /usr/src
          cd /usr/src
          git clone -j "$(nproc)" --depth=1 --branch "$LINUX_BRANCH" $KERNEL_URL "linux"
          cd -

      - name: provide source file
        run: |
          cat <<EOF > ~/source-me.sh
          export CROSS_COMPILE=aarch64-linux-gnu-
          export ARCH=arm64
          export KERNEL=kernel8
          export KDEFCONFIG_NAME=bcm2711_defconfig
          export KERNELDIR=/usr/src/linux
          EOF

      - run: date

      - name: build kernel sources once
        run: |
          source ~/source-me.sh
          cd $KERNELDIR
          make $KDEFCONFIG_NAME
          make -j$(nproc) Image.gz modules dtbs

## basics
      - run: source ~/source-me.sh && cd ./010__basics/basics01__hello && make
      - run: source ~/source-me.sh && cd ./010__basics/basics02__hello && make
      - run: source ~/source-me.sh && cd ./010__basics/basics03__hello && make
      - run: source ~/source-me.sh && cd ./010__basics/basics04__hello_module_init_arguments && make
      - run: source ~/source-me.sh && cd ./010__basics/basics05__hello_module_init_arguments && make
      - run: source ~/source-me.sh && cd ./010__basics/basics06__hello_multiple_files && make
      - run: source ~/source-me.sh && cd ./010__basics/basics07__hello_chardev_driver && make
      - run: source ~/source-me.sh && cd ./010__basics/basics08__hello_procfs_read && make
      - run: source ~/source-me.sh && cd ./010__basics/basics09__hello_procfs_read_write && make
      - run: source ~/source-me.sh && cd ./010__basics/basics10__hello_procfs_fops && make
      - run: source ~/source-me.sh && cd ./010__basics/basics11__hello_procfs_seq_filesystem && make
      - run: source ~/source-me.sh && cd ./010__basics/basics12__hello-with-timing && make
      - run: source ~/source-me.sh && cd ./010__basics/device__01_static_major_minor && make
      - run: source ~/source-me.sh && cd ./010__basics/device__02_dynamic_major_minor && make
      - run: source ~/source-me.sh && cd ./010__basics/kbuild__symbol_export_to_another_module && make
      - run: source ~/source-me.sh && cd ./010__basics/types && make

## character device
      - run: source ~/source-me.sh && cd ./020__chardev/010__mknod && make
      - run: source ~/source-me.sh && cd ./020__chardev/012__devicefile && make
      - run: source ~/source-me.sh && cd ./020__chardev/013__devicefile_and_chardev && make
      - run: source ~/source-me.sh && cd ./020__chardev/014__devicefile_implemented && make
      - run: source ~/source-me.sh && cd ./020__chardev/020__linkedlist && make
      - run: source ~/source-me.sh && cd ./020__chardev/030__wait_on_events && make
      - run: source ~/source-me.sh && cd ./020__chardev/110__ioctl && make
      - run: source ~/source-me.sh && cd ./020__chardev/112__ioctl_string_disabled && make
      - run: source ~/source-me.sh && cd ./020__chardev/113__ioctl_signal && make
      - run: source ~/source-me.sh && cd ./020__chardev/120__ioctl_demo && make
      - run: source ~/source-me.sh && cd ./020__chardev/121__using_devtmpfs_with_device_class && make
      - run: source ~/source-me.sh && cd ./020__chardev/122__using_miscdevice && make

# TODO
