name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install build-essential
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: install acl lib
        run: |
          sudo apt-get install -y libacl1-dev

      - name: install caps lib (classic, not -ng)
        run: |
          sudo apt-get install -y libcap-dev

      - name: install gcc/g++
        run: |
          sudo apt-get install -y gcc g++

      - name: install nasm
        run: |
          sudo apt-get install -y nasm

      - name: install libc6-dev
        run: |
          sudo apt-get install -y libc6-dev

      - name: install cunit
        run: |
          sudo apt-get install -y libcunit1-ncurses-dev

      - name: install clang
        run: |
          sudo apt-get install -y clang clang-tools clang-format

      - name: install cmake
        run: |
          sudo apt-get install -y cmake

      - run: date

## 00: basics
## TODO
#      - run: cd ./00_language-basics/atoi02 && make && ./*.elf
# -> github__c_linux/010__basics/basics01__hello
