name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install build-essential
        run: |
          sudo apt-get update
          sudo apt-get install -y crossbuild-essential-arm64

      - name: install gcc/g++
        run: |
          sudo apt-get install -y gcc g++

      - name: install debhelper
        run: |
          sudo apt-get install -y debhelper

      - name: install DT compiler
        run: |
          sudo apt-get install -y device-tree-compiler

      - name: install libc6-dev
        run: |
          sudo apt-get install -y libc6-dev

      - name: install cunit
        run: |
          sudo apt-get install -y libcunit1-ncurses-dev

      - name: install clang
        run: |
          sudo apt-get install -y clang clang-tools clang-format

      - name: install cmake
        run: |
          sudo apt-get install -y cmake

      - name: rpi kernel sources
        run: |
          export LINUX_BRANCH="rpi-6.3.y"
          export KDEFCONFIG_NAME="bcm2711_defconfig"
          export KERNEL_URL="https://github.com/raspberrypi/linux"
          sudo chown $(whoami):$(whoami) -R /usr/src
          cd /usr/src
          git clone -j "$(nproc)" --depth=1 --branch "$LINUX_BRANCH" $KERNEL_URL "linux"

      - name: provide source file
        run: |
          cat <<EOF > ~/source-me.sh
          export CROSS_COMPILE=aarch64-linux-gnu-
          export ARCH=arm64
          export KERNEL=kernel8
          export KDEFCONFIG_NAME=bcm2711_defconfig
          export KERNELDIR=/usr/src/linux
          EOF

      - run: date

      - name: build kernel sources once
        run: |
          source ~/source-me.sh
          cd $KERNELDIR
          make $KDEFCONFIG_NAME
          make -j$(nproc) Image.gz modules dtbs

## 00: basics
      - run: source ~/source-me.sh && cd ./010__basics/basics01__hello && make && ./*.elf
# TODO
